services:
  tcp-echo-server:
    build: .
    container_name: tcp-echo
    ports:
      - "4242:4242"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - eth_network
networks:
  eth_network:
    driver: bridge